const { Room } = require('../data'); // Asegúrate de que el modelo Room esté correctamente configurado

const loadRooms = async () => {
    try {
        const rooms = [
            {
                roomNumber: 101,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [

                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Doble",
                status: null,
                maxGuests: 3,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 102,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741903681/packs/s8sjhxenmbbhuihefvfl.png",
                ],
                type: "Triple",
                status: null,
                maxGuests: 3,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 103,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Cuadruple",
                status: null,
                maxGuests: 8,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 104,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Cuadruple",
                status: null,
                maxGuests: 4,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 105,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",

                ],
                type: "Cuadruple",
                status: null,
                maxGuests: 4,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 106,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741903636/packs/tmtyuenykidfex4e4l5c.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Cuadruple",
                status: null,
                maxGuests: 4,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 107,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Cuadruple",
                status: null,
                maxGuests: 4,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 108,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741903636/packs/tmtyuenykidfex4e4l5c.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Pareja",
                status: null,
                maxGuests: 2,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 109,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741903636/packs/tmtyuenykidfex4e4l5c.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Cuadruple",
                status: null,
                maxGuests: 4,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 110,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741903636/packs/tmtyuenykidfex4e4l5c.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Sencilla",
                status: null,
                maxGuests: 1,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 111,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                   
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Cuadruple",
                status: null,
                maxGuests: 8,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 112,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741903636/packs/tmtyuenykidfex4e4l5c.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Triple",
                status: null,
                maxGuests: 4,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 113,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741903636/packs/tmtyuenykidfex4e4l5c.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Cuadruple",
                status: null,
                maxGuests: 4,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 114,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741903636/packs/tmtyuenykidfex4e4l5c.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Doble",
                status: null,
                maxGuests: 3,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 115,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741903636/packs/tmtyuenykidfex4e4l5c.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Cuadruple",
                status: null,
                maxGuests: 4,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 116,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                   "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
				   "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Cuadruple",
                status: null,
                maxGuests: 4,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 117,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                   
                ],
                type: "Cuadruple",
                status: null,
                maxGuests: 4,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 118,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Cuadruple",
                status: null,
                maxGuests: 4,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 119,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                  
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Cuadruple",
                status: null,
                maxGuests: 4,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 120,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741903636/packs/tmtyuenykidfex4e4l5c.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Cuadruple",
                status: null,
                maxGuests: 4,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 121,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                   
                ],
                type: "Cuadruple",
                status: null,
                maxGuests: 4,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 122,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                   
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Cuadruple",
                status: null,
                maxGuests: 4,
                isActive: true,
                Services: [],
            },
            {
                roomNumber: 123,
                description: "Habitación completa",
                price: "70000.00",
                available: false,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                  
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/bqbv8wdpdxdujyycjam8.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/nddesbjmbt7lo1yjbblt.png",
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741921960/packs/mde0kduevtv9ymofknhs.png",
                ],
                type: "Cuadruple",
                status: null,
                maxGuests: 4,
                isActive: true,
                Services: [],
            },
        ];

        // Generar habitaciones del 103 al 123 automáticamente
        for (let i = 103; i <= 123; i++) {
            rooms.push({
                roomNumber: i,
                description: "Habitación estándar",
                price: "100000.00",
                available: true,
                isPromo: false,
                promotionPrice: null,
                image_url: [
                    "https://res.cloudinary.com/dv1xvijmn/image/upload/v1741903681/packs/s8sjhxenmbbhuihefvfl.png",
                ],
                type: "Doble",
                status: null,
                maxGuests: 2,
                isActive: true,
            });
        }
        rooms.sort((a, b) => a.roomNumber - b.roomNumber);
        // Insertar habitaciones en la base de datos
        for (const room of rooms) {
            const existingRoom = await Room.findOne({ where: { roomNumber: room.roomNumber } });
            if (!existingRoom) {
                await Room.create(room);
            }
        }

        console.log("Habitaciones cargadas correctamente.");
    } catch (error) {
        console.error("Error al cargar las habitaciones:", error);
    }
};

module.exports = loadRooms;